### ISSUE TITLE
解决函数识别不完整

### ISSUE THREAD

**Issue by L0yy** [0xjiayu/go_parser#1]
测试了恢复在windows和linux上编译的的hello world，结果IDA识别的函数远远少于Functions number的值，在windows上还找不到main😶
通过检查发现是IDA未能识别某些函数，需要手动创建函数
在https://github.com/0xjiayu/go_parser/blob/master/pclntbl.py#L109 下面加上如下代码解决了这个问题😋
```
if not idc.GetFunctionName(func_addr):
    # common._debug("Defining function at: @ %x" % func_addr)
    idc.MakeCode(func_addr)
    idc.MakeFunction(func_addr)
```

**Comment by 0xjiayu** [comment]
感谢指正，已更新。

**Comment by fzxcp3** [comment]
/opt/go_parser/go_parser.py: in method 'create_strlit', argument 2 of type 'size_t'
Traceback (most recent call last):
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/ida_idaapi.py", line 553, in IDAPython_ExecScript
    execfile(script, g)
  File "/opt/go_parser/go_parser.py", line 52, in <module>
    main()
  File "/opt/go_parser/go_parser.py", line 36, in main
    pclntab.parse()
  File "/opt/go_parser/pclntbl.py", line 173, in parse
    self.parse_funcs()
  File "/opt/go_parser/pclntbl.py", line 125, in parse_funcs
    func_st.parse()
  File "/opt/go_parser/pclntbl.py", line 252, in parse
    if idc.MakeStr(name_addr, name_addr + len(raw_name_str) + 1):
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/idc_bc695.py", line 113, in MakeStr
    def MakeStr(ea, endea): return create_strlit(ea, 0 if (endea) == ida_idaapi.BADADDR else endea-ea)
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/idc.py", line 695, in create_strlit
    return ida_bytes.create_strlit(ea, 0 if endea == BADADDR else endea - ea, get_inf_attr(INF_STRTYPE))
  File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/ida_bytes.py", line 1618, in create_strlit
    return _ida_bytes.create_strlit(*args)
TypeError: in method 'create_strlit', argument 2 of type 'size_t'

**Comment by 0xjiayu** [comment]
> /opt/go_parser/go_parser.py: in method 'create_strlit', argument 2 of type 'size_t'
> Traceback (most recent call last):
> File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/ida_idaapi.py", line 553, in IDAPython_ExecScript
> execfile(script, g)
> File "/opt/go_parser/go_parser.py", line 52, in
> main()
> File "/opt/go_parser/go_parser.py", line 36, in main
> pclntab.parse()
> File "/opt/go_parser/pclntbl.py", line 173, in parse
> self.parse_funcs()
> File "/opt/go_parser/pclntbl.py", line 125, in parse_funcs
> func_st.parse()
> File "/opt/go_parser/pclntbl.py", line 252, in parse
> if idc.MakeStr(name_addr, name_addr + len(raw_name_str) + 1):
> File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/idc_bc695.py", line 113, in MakeStr
> def MakeStr(ea, endea): return create_strlit(ea, 0 if (endea) == ida_idaapi.BADADDR else endea-ea)
> File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/idc.py", line 695, in create_strlit
> return ida_bytes.create_strlit(ea, 0 if endea == BADADDR else endea - ea, get_inf_attr(INF_STRTYPE))
> File "/Applications/IDA Pro 7.0/ida64.app/Contents/MacOS/python/ida_bytes.py", line 1618, in create_strlit
> return _ida_bytes.create_strlit(*args)
> TypeError: in method 'create_strlit', argument 2 of type 'size_t'

这个是 IDA7.0 中 IDAPython MakeStr() API 实现的问题。修复方式参考看雪论坛这篇帖子：
https://bbs.pediy.com/thread-229574.htm
