### ISSUE TITLE
解析的时候容易造成IDA主程序长时间无响应，且解析失败

### ISSUE THREAD

**Issue by allenxian** [0xjiayu/go_parser#16]
![image](https://user-images.githubusercontent.com/22782166/119936574-f67b5700-bfbb-11eb-997c-e76a73157276.png)

**Comment by justtsuj** [comment]
原本的代码中使用idc.BADADDR，作为寻找的边界，这样最坏的情况要遍历2^32次，造成长时间无响应。在ida 7.5 python3情况下可以使用下面的代码暂时缓解该问题。
![image](https://user-images.githubusercontent.com/26221347/122200354-8b8fb280-cecd-11eb-8fa8-6a3deebe8dc1.png)

**Comment by zichen8552** [comment]
图片看不见了，能发一下代码吗？

**Comment by 0xjiayu** [comment]
感谢指正，已 Fix。现在代码库已更新，请更新代码后再试一下。
