### ISSUE TITLE
ida7.7解析go X86_64下报错Invalid pclntbl header magic number!

### ISSUE THREAD

**Issue by Pancho-hub** [0xjiayu/go_parser#18]
似乎是解析头报错了。。是程序做了什么处理导致的吗
 #[
![2~TH_({AI8DGBY GZ3OHXBC](https://user-images.githubusercontent.com/54937059/198974787-0a974e3a-7ad3-4f4f-a88f-b70a56a5052f.png)
](url)

**Comment by 0xjiayu** [comment]
是 go_parser 解析二进制程序失败了，不过我需要更多信息才能定位具体报错的原因，您方便提供二进制文件吗？
