### ISSUE TITLE
There an issue for parser_func.py

### ISSUE THREAD

**Issue by wudifengz** [0xjiayu/go_parser#19]
I use the go_parser on IDA 7.6 but there an issuse on it. The following is the error report:
  File "D:/xxxxxxxx/IDA Pro 7.6/plugins/parse_func.py", line 12, in <module>
    start = idc.get_func_attr(here(),FUNCATTR_START)
NameError: name 'here' is not defined

is there some modul i did not install or something other reasen?

by the way, I use local python (version 3.10.8 ).

**Comment by 0xjiayu** [comment]
Sorry, it's my fault. **parse_func.py** is just a script for testing some functions, and I should have deleted that.

To use go_parser, you just need to run **go_parser.py** in IDA.
