### ISSUE TITLE
关于idapython api版本和python版本

### ISSUE THREAD

**Issue by wonderkun** [0xjiayu/go_parser#2]
两个问题
1. 尽量去支持最新版本的idapython的api，这样才能在以后版本不出问题。
2. python2都已经废弃了，python3才是主流。

我对两个问题都进行了fix，但是可能存在一些小的bug，我可以发pull requests吗？

**Comment by 0xjiayu** [comment]
抱歉，我手上没有更高版本的 IDAPro，也没测试更高版本的 IDAPython 和最新的 API，只在 IDAPro 7.0/7.2 版本上做了测试。
欢迎发 PR

**Comment by wonderkun** [comment]
好的
