### ISSUE TITLE
ida 7.7 and pytho 3.8, i got this: Failed to find firstmoduledata address! in moduledata.py, line 177, Please help

### ISSUE THREAD

**Issue by onlyU22** [0xjiayu/go_parser#20]

**Comment by 0xjiayu** [comment]
go_parser will find the firstmoduledata struct via Go Runtime magic number. If it prints out this err msg, it always means there is really no standard magic number in the Go binary file.

Maybe the magic number was modified to another value.

**Comment by pkujhd** [comment]
golang1.20 use new magic number,change F0 toF1

**Comment by 0xjiayu** [comment]
> golang1.20 use new magic number,change F0 toF1

Yeah, that's also a possible situation. But go_parser has not been adapted to Go1.2x yet, that will be soon :-）

**Comment by MuelNova** [comment]
> 

Simply change the  magic number will cause some other exceptions. Hopefully we can get the new version soon :heart:
